name:                ingcsv2hledger
version:             0.1.0.0
github:              "bneijt/ingcsv2hledger"
license:             GPLv3
author:              "Bram Neijt"
maintainer:          "bneijt@gmail.com"
copyright:           "2018 Bram Neijt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ingcsv2hledger#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    dependencies:
        - cassava
        - attoparsec
        - bytestring
        - text
        - vector
        - unordered-containers
        - text-show
        - Decimal
        - time
        - uuid

executables:
  ingcsv2hledger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ingcsv2hledger

tests:
  ingcsv2hledger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ingcsv2hledger
