version: 2
jobs:
    build:
        docker:
            - image: fpco/stack-build
        steps:
            - checkout
            - run:
                name: Build
                command: stack build
            - run:
                name: Test
                command: stack test
